name: AppQCHUI
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_animate: ^4.0.0
  firebase_core: 
  firebase_auth: 
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  

flutter_native_splash:
  color: "#c39a4c"
  image: assets/images/logoQCHUI.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/llama.png
    - assets/images/qchui.png
    - assets/images/logoQCHUI.png
    - assets/verbos.json
  