// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjR_9pDir9eOcFX1zm71MSyFxKJs1ceL0',
    appId: '1:423458236232:web:3220c4be5618689a7cb57d',
    messagingSenderId: '423458236232',
    projectId: 'qchui-1d689',
    authDomain: 'qchui-1d689.firebaseapp.com',
    storageBucket: 'qchui-1d689.firebasestorage.app',
    measurementId: 'G-8D4EQ0B247',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9eDXISbSV6INqslsrWhphgZLXRv2344',
    appId: '1:423458236232:android:f98d63ceab2793627cb57d',
    messagingSenderId: '423458236232',
    projectId: 'qchui-1d689',
    storageBucket: 'qchui-1d689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQdqYrpyH9Ns39sBVfZT0i1PDQnehdGI',
    appId: '1:423458236232:ios:e1d3ba3a0101c7227cb57d',
    messagingSenderId: '423458236232',
    projectId: 'qchui-1d689',
    storageBucket: 'qchui-1d689.firebasestorage.app',
    iosBundleId: 'com.example.appchua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhQdqYrpyH9Ns39sBVfZT0i1PDQnehdGI',
    appId: '1:423458236232:ios:e1d3ba3a0101c7227cb57d',
    messagingSenderId: '423458236232',
    projectId: 'qchui-1d689',
    storageBucket: 'qchui-1d689.firebasestorage.app',
    iosBundleId: 'com.example.appchua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjR_9pDir9eOcFX1zm71MSyFxKJs1ceL0',
    appId: '1:423458236232:web:1572a92b463870087cb57d',
    messagingSenderId: '423458236232',
    projectId: 'qchui-1d689',
    authDomain: 'qchui-1d689.firebaseapp.com',
    storageBucket: 'qchui-1d689.firebasestorage.app',
    measurementId: 'G-HFYQ4MMVLY',
  );
}
